# Generated by Django 2.2.1 on 2019-05-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190509_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.IntegerField()),
                ('poids', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
