# Generated by Django 2.2.1 on 2019-05-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190511_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poids',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='taille',
            field=models.IntegerField(default=0),
        ),
    ]
