# Generated by Django 2.2.1 on 2019-05-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190514_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gout',
            name='gout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='gout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
